name: Go Test

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5S
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v .